language: python
python: 2.7
env:
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libcap
install:
  - pip install tox
  - pip install python-coveralls
script:
  - tox -e $TOX_ENV
after_success:
  coveralls
